version: '3.3'

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "STRONG!Pas1"
    networks:
      - app-network
    ports:
      - 1433:1433
    volumes:
      - my-volume:/var/opt/mssql

  app:
    image: tax-tool-image
    build:
      context: .
      dockerfile: TaxTool/Dockerfile
    container_name: tax-tool
    ports:
      - "8080:8080"
    depends_on:
      - mssql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  my-volume: